INSERT INTO sources (name, url, is_seeded) VALUES
    ('Preston Thorpe', 'https://pthorpe92.dev/atom.xml', 1),
    ('Lobsters', 'https://lobste.rs/rss', 1),
    ('Hacker News', 'https://hnrss.org/frontpage', 1),
    ('Hacker News Atom', 'https://hnrss.org/frontpage.atom', 1),
    ('Hacker News Points', 'https://hnrss.org/show?points=25', 1),
    ('Hacker News RSS', 'https://news.ycombinator.com/rss', 1),
    ('Dev.to', 'https://dev.to/feed', 1),
    ('Simon Willison Everything', 'https://simonwillison.net/atom/everything/', 1),
    ('Simon Willison Links', 'https://simonwillison.net/atom/links/', 1),
    ('Daring Fireball', 'https://daringfireball.net/feeds/main', 1),
    ('Waxy.org', 'https://waxy.org/feed/', 1),
    ('Kottke.org', 'https://feeds.kottke.org/main', 1),
    ('Dan Luu', 'https://danluu.com/atom.xml', 1),
    ('Eli Bendersky', 'https://eli.thegreenplace.net/feeds/all.atom.xml', 1),
    ('Brandur Leach', 'https://brandur.org/articles.atom', 1),
    ('Angelo Fallaria', 'https://angelo.fallaria.com/rss.xml', 1),
    ('Uncomfy Halo Macro', 'https://uncomfyhalomacro.pl/atom.xml', 1),
    ('Ryana Aque', 'https://www.ryanaque.com/rss.xml', 1),
    ('AC Open Source', 'https://ac-opensource.github.io/blog/rss.xml', 1) 
ON CONFLICT DO NOTHING;

INSERT INTO interests (keyword, anchor) VALUES
    ('go', 'software.n.01'),
    ('golang', 'software.n.01'),
    ('frontend', 'software.n.01'),
    ('front end', 'software.n.01'),
    ('backend', 'software.n.01'),
    ('back end', 'software.n.01'),
    ('coding', 'software.n.01'),
    ('programming', 'software.n.01'),
    ('software engineering', 'software.n.01'),
    ('software', 'software.n.01'),
    ('typescript', 'software.n.01'),
    ('ts', 'software.n.01'),
    ('database', 'database.n.01'),
    ('orm', 'database.n.01'),
    ('orms', 'database.n.01'),
    ('sql', 'database.n.01'),
    ('sqlite', 'database.n.01'),
    ('postgres', 'database.n.01'),
    ('postgresql', 'database.n.01'),
    ('mysql', 'database.n.01'),
    ('linux', 'operating_system.n.01'),
    ('python', 'programming_language.n.01'),
    ('javascript', 'programming_language.n.01'),
    ('rust', 'programming_language.n.01'),
    ('java', 'programming_language.n.01'),
    ('kotlin', 'programming_language.n.01'),
    ('swift', 'programming_language.n.01'),
    ('ruby', 'programming_language.n.01'),
    ('php', 'programming_language.n.01'),
    ('elixir', 'programming_language.n.01'),
    ('haskell', 'programming_language.n.01'),
    ('react', 'software.n.01'),
    ('vue', 'software.n.01'),
    ('svelte', 'software.n.01'),
    ('angular', 'software.n.01'),
    ('next.js', 'software.n.01'),
    ('node.js', 'software.n.01'),
    ('django', 'software.n.01'),
    ('fastapi', 'software.n.01'),
    ('rails', 'software.n.01'),
    ('spring boot', 'software.n.01'),
    ('git', 'software.n.01'),
    ('github', 'software.n.01'),
    ('docker', 'software.n.01'),
    ('kubernetes', 'software.n.01'),
    ('terraform', 'software.n.01'),
    ('ansible', 'software.n.01'),
    ('open source', 'software.n.01'),
    ('devops', 'software.n.01'),
    ('unit testing', 'software.n.01'),
    ('integration testing', 'software.n.01'),
    ('redis', 'database.n.01'),
    ('mongodb', 'database.n.01'),
    ('mariadb', 'database.n.01'),
    ('duckdb', 'database.n.01'),
    ('nosql', 'database.n.01'),
    ('freebsd', 'operating_system.n.01'),
    ('ubuntu', 'operating_system.n.01'),
    ('debian', 'operating_system.n.01'),
    ('android', 'operating_system.n.01'),
    ('macos', 'operating_system.n.01'),
    ('compiler', 'compiler.n.02'),
    ('llvm', 'compiler.n.02'),
    ('gcc', 'compiler.n.02'),
    ('algorithm', 'algorithm.n.01'),
    ('algorithms', 'algorithm.n.01'),
    ('data structures', 'computer_science.n.01'),
    ('computer science', 'computer_science.n.01'),
    ('artificial intelligence', 'artificial_intelligence.n.01'),
    ('machine learning', 'artificial_intelligence.n.01'),
    ('deep learning', 'artificial_intelligence.n.01'),
    ('neural networks', 'artificial_intelligence.n.01'),
    ('large language models', 'artificial_intelligence.n.01'),
    ('llm', 'artificial_intelligence.n.01'),
    ('robotics', 'robotics.n.01'),
    ('cryptography', 'cryptography.n.02'),
    ('encryption', 'cryptography.n.02'),
    ('tls', 'cryptography.n.02'),
    ('networking', 'computer_network.n.01'),
    ('tcp', 'computer_network.n.01'),
    ('http', 'computer_network.n.01'),
    ('dns', 'computer_network.n.01'),
    ('hardware', 'hardware.n.03'),
    ('gpu', 'hardware.n.03'),
    ('cpu', 'microprocessor.n.01'),
    ('microcontroller', 'hardware.n.03'),
    ('raspberry pi', 'hardware.n.03'),
    ('infrastructure as code', 'software.n.01'),
    ('configuration management', 'software.n.01'),
    ('platform engineering', 'software.n.01'),
    ('site reliability engineering', 'software.n.01'),
    ('sre', 'software.n.01'),
    ('gitops', 'software.n.01'),
    ('ci/cd', 'software.n.01'),
    ('continuous integration', 'software.n.01'),
    ('continuous delivery', 'software.n.01'),
    ('continuous deployment', 'software.n.01'),
    ('github actions', 'software.n.01'),
    ('gitlab ci', 'software.n.01'),
    ('jenkins', 'software.n.01'),
    ('argocd', 'software.n.01'),
    ('argo cd', 'software.n.01'),
    ('fluxcd', 'software.n.01'),
    ('tekton', 'software.n.01'),
    ('pulumi', 'software.n.01'),
    ('opentofu', 'software.n.01'),
    ('packer', 'software.n.01'),
    ('vagrant', 'software.n.01'),
    ('puppet', 'software.n.01'),
    ('nixos', 'operating_system.n.01'),
    ('talos linux', 'operating_system.n.01'),
    ('k8s', 'software.n.01'),
    ('helm', 'software.n.01'),
    ('kustomize', 'software.n.01'),
    ('podman', 'software.n.01'),
    ('containerd', 'software.n.01'),
    ('nomad', 'software.n.01'),
    ('virtualization', 'software.n.01'),
    ('proxmox', 'software.n.01'),
    ('qemu', 'software.n.01'),
    ('observability', 'software.n.01'),
    ('prometheus', 'software.n.01'),
    ('grafana', 'software.n.01'),
    ('opentelemetry', 'software.n.01'),
    ('jaeger', 'software.n.01'),
    ('fluent bit', 'software.n.01'),
    ('fluentd', 'software.n.01'),
    ('elasticsearch', 'software.n.01'),
    ('opensearch', 'software.n.01'),
    ('nginx', 'software.n.01'),
    ('haproxy', 'software.n.01'),
    ('traefik', 'software.n.01'),
    ('envoy', 'software.n.01'),
    ('istio', 'software.n.01'),
    ('linkerd', 'software.n.01'),
    ('cilium', 'software.n.01'),
    ('consul', 'software.n.01'),
    ('etcd', 'database.n.01'),
    ('hashicorp vault', 'software.n.01'),
    ('cert-manager', 'software.n.01'),
    ('cloud computing', 'computer_network.n.01'),
    ('aws', 'computer_network.n.01'),
    ('amazon web services', 'computer_network.n.01'),
    ('azure', 'computer_network.n.01'),
    ('google cloud', 'computer_network.n.01'),
    ('self hosting', 'computer_network.n.01'),
    ('self-hosting', 'computer_network.n.01'),
    ('homelab', 'computer_network.n.01'),
    ('load balancing', 'computer_network.n.01'),
    ('service mesh', 'computer_network.n.01'),
    ('service discovery', 'computer_network.n.01')
ON CONFLICT DO NOTHING;
